title: Kaushika Gigan Rupasinghe
logo: assets/dp.jpg
description: I am a Machine Learning Engineer with a strong background in Computer Vision, Natural Language Processing (NLP), Large Language Models (LLMs), and Audio Processing. With expertise in deep learning, generative AI, and model deployment, I build cutting-edge AI solutions that drive automation, enhance decision-making, and improve user experiences.
show_downloads: true
theme: jekyll-theme-minimal
