title: Kaushika Gihan Rupasinghe
logo: assets/dp.jpg
#description: 
show_downloads: true
theme: jekyll-theme-modernist
#jekyll-theme-minimal
#jekyll-theme-architect
#jekyll-theme-midnight
#jekyll-theme-dinky
#jekyll-theme-leap-day
#jekyll-theme-merlot
#jekyll-theme-modernist
