title: Kaushika Gihan Rupasinghe
logo: assets/dp.jpg
description: I am a Machine Learning Engineer with a strong background in Computer Vision, Natural Language Processing (NLP), Large Language Models (LLMs).
contact:
  email: "your.email@example.com"
  phone: "+1234567890"
  linkedin: "https://www.linkedin.com/in/yourprofile"
  github: "https://github.com/yourusername"
  twitter: "https://twitter.com/yourusername"
theme: jekyll-theme-architect
#jekyll-theme-minimal
